#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    leftToRight = 0
    rightToLeft = 0
    i = 0
    j = len(arr)-1
    while i < len(arr):
        leftToRight += arr[i][i]
        rightToLeft += arr[i][j]
        
        i+=1
        j-=1
    return abs(leftToRight-rightToLeft)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
