#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    final = ""
    if "AM" in s:
        if "12" in s[0:2]:
            final = "00" + str[2:8]
        else:
            final = s[0:8]
    elif "PM" in s:
        if "12" in s[0:2]:
            final = s[0:8]
        else:
            first = str(int(s[0:2]) + 12)
            final = first + s[2:8]        
    return final

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
